'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';

type ScheduleRow={id:string;priority:number|null;job:string|null;model:string|null;serial:string|null;status:string|null;boom:string|null};
type ModelPart={model:string;part_name:string;part_number:string|null;quantity:number;location:string|null};
type RequestPart={id:string;part_name:string;part_number:string|null;quantity:number;delivered:boolean;reservation_status:string|null};
type RequestRow={id:string;model:string|null;machine_serial:string|null;status:string;assigned_handler:string|null;request_parts?:RequestPart[]};
type SavedUser={username?:string;name?:string;role?:string};
type ModelPlan=ScheduleRow&{required:ModelPart[];requested:RequestPart[]};

const partIcon:Record<string,string>={'base boom':'▰','inner mid':'▱','outer mid':'▱','small mid':'▱','fly boom':'▰','lower push tube':'╱','upper push tube':'╱','telescope':'◉','telescope cylinder':'◉','power track t/t':'⛓','power track upper':'⛓'};
function key(p:{part_name:string;part_number?:string|null}){return `${p.part_name}|${p.part_number??''}`}
function icon(name:string){const n=name.toLowerCase();return Object.entries(partIcon).find(([k])=>n.includes(k))?.[1]??'▰'}

export default function BoomDeliveryPlan(){
 const [schedule,setSchedule]=useState<ScheduleRow[]>([]),[parts,setParts]=useState<ModelPart[]>([]),[requests,setRequests]=useState<RequestRow[]>([]);
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[user,setUser]=useState<SavedUser|null>(null);
 async function load(){const [s,p,r]=await Promise.all([supabase.from('production_schedule').select('id, priority, job, model, serial, status, boom').order('priority',{ascending:true}),supabase.from('model_parts').select('model, part_name, part_number, quantity, location').eq('material_type','Boom').eq('active',true).order('part_name'),supabase.from('material_requests').select('id, model, machine_serial, status, assigned_handler, request_parts(id, part_name, part_number, quantity, delivered, reservation_status)').eq('material_type','Boom').order('requested_at',{ascending:false})]);if(s.error||p.error||r.error)setMessage('Unable to load the live boom delivery plan.');else{setSchedule((s.data??[]) as ScheduleRow[]);setParts((p.data??[]) as ModelPart[]);setRequests((r.data??[]) as RequestRow[]);setMessage('')}setLoading(false)}
 useEffect(()=>{try{const u=localStorage.getItem('lineflowUser');if(u)setUser(JSON.parse(u))}catch{}load();const c=supabase.channel('boom-delivery-plan').on('postgres_changes',{event:'*',schema:'public',table:'production_schedule'},load).on('postgres_changes',{event:'*',schema:'public',table:'material_requests'},load).on('postgres_changes',{event:'*',schema:'public',table:'request_parts'},load).on('postgres_changes',{event:'*',schema:'public',table:'model_parts'},load).subscribe();return()=>{supabase.removeChannel(c)}},[]);
 const plans=useMemo<ModelPlan[]>(()=>schedule.filter(x=>!!x.model).map(row=>{const required=parts.filter(p=>p.model===row.model),matching=requests.filter(r=>r.model===row.model&&(!row.serial||!r.machine_serial||r.machine_serial===row.serial)),latest=new Map<string,RequestPart>();for(const r of matching)for(const p of r.request_parts??[])if(!latest.has(key(p)))latest.set(key(p),p);return{...row,required,requested:[...latest.values()]}}),[schedule,parts,requests]);
 const totals=useMemo(()=>plans.reduce((a,p)=>{a.required+=p.required.length;a.delivered+=p.required.filter(x=>p.requested.find(r=>key(r)===key(x))?.delivered).length;return a},{required:0,delivered:0}),[plans]);
 const remaining=Math.max(0,totals.required-totals.delivered),overall=totals.required?Math.round(totals.delivered/totals.required*100):0,isMike=user?.username==='line1';
 return <section className="sectionBlock boomDeliveryPlan">
  <div className="scheduleHeader"><div><p className="eyebrow">{isMike?'Boom Assembly Supervisor · Live Board':'Visual Material Readiness'}</p><h2>Today&apos;s Boom Delivery Plan</h2><p className="dashboardRole">{isMike?'Mike’s live view of the parts Greg and Jose need to deliver for today’s boom assembly plan.':'Required boom parts for each model in today’s production schedule, matched to live delivery activity.'}</p></div></div>
  <div className="dashboardGrid"><div className="metricCard"><span>Models Today</span><strong>{plans.length}</strong><p>Scheduled boom models</p></div><div className="metricCard"><span>Parts Delivered</span><strong>{totals.delivered}</strong><p>Required part types delivered</p></div><div className="metricCard"><span>Parts Remaining</span><strong>{remaining}</strong><p>Required part types still needed</p></div><div className="metricCard"><span>Overall Progress</span><strong>{overall}%</strong><div style={{height:8,borderRadius:999,background:'rgba(148,163,184,.16)',overflow:'hidden',marginTop:8}}><div style={{height:'100%',width:`${overall}%`,background:'currentColor'}}/></div></div></div>
  {message&&<p className="requestMessage">{message}</p>}
  {loading?<p className="scheduleFootnote">Loading live boom delivery plan...</p>:plans.length===0?<p className="scheduleFootnote">Add models to today&apos;s production schedule to build the delivery plan.</p>:<div className="boomPlanList">{plans.map(plan=>{const delivered=plan.required.filter(p=>plan.requested.find(r=>key(r)===key(p))?.delivered).length,percent=plan.required.length?Math.round(delivered/plan.required.length*100):0,pending=plan.required.filter(p=>!plan.requested.find(r=>key(r)===key(p))?.delivered);return <article className="requestCard" key={plan.id}>
   <div className="requestCardTop"><div><span className="requestLine">Priority {plan.priority??'—'} · {plan.job?`Job ${plan.job}`:'Today’s Plan'}</span><h3 style={{fontSize:'1.7rem'}}>{plan.model}</h3><p className="dashboardRole">Serial {plan.serial||'Not entered'} · {plan.status||'Planned'}</p></div><div style={{minWidth:180}}><strong>{delivered} of {plan.required.length} Parts Delivered</strong><div style={{height:10,borderRadius:999,background:'rgba(148,163,184,.16)',overflow:'hidden',marginTop:8}}><div style={{height:'100%',width:`${percent}%`,background:'currentColor'}}/></div><small>{percent}% complete</small></div></div>
   {plan.required.length===0?<p className="requestNotes">No boom parts have been configured for this model yet.</p>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10,marginTop:16}}>{plan.required.map(part=>{const a=plan.requested.find(r=>key(r)===key(part)),done=!!a?.delivered,short=!done&&['Short','No Inventory Match'].includes(a?.reservation_status??''),state=done?'✓ Delivered':short?'⚠ Not in Stock':'◷ Pending';return <div key={key(part)} style={{padding:12,border:'1px solid rgba(148,163,184,.22)',borderRadius:12,background:done?'rgba(16,185,129,.08)':short?'rgba(239,68,68,.07)':'rgba(245,158,11,.05)'}}><div style={{fontSize:'1.8rem',lineHeight:1,marginBottom:9}}>{icon(part.part_name)}</div><strong>{part.part_name}</strong><small style={{display:'block',marginTop:4}}>#{part.part_number||'Not set'}</small><small style={{display:'block'}}>Qty {part.quantity} · {part.location||'Location not set'}</small><span className={`priorityBadge ${short?'priorityUrgent':''}`} style={{display:'inline-block',marginTop:9}}>{state}</span></div>})}</div>}
   <div className="requestTiming" style={{marginTop:16}}><span><strong>Next Needed:</strong> {pending.slice(0,3).map(p=>`${p.part_name}${p.part_number?` (#${p.part_number})`:''}`).join(' · ')||'All required parts delivered'}</span><span>Delivery team: Greg + Jose</span></div>
  </article>})}</div>}
  <div className="scheduleFootnote" style={{display:'flex',gap:18,flexWrap:'wrap'}}><span>✓ Delivered</span><span>◷ Pending</span><span>⚠ Not in Stock</span><span>Statuses come from live request/inventory activity — no mock completion data.</span></div>
 </section>
}
