'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';

type InventoryItem={id:string;material_type:string;material_name:string;part_number:string|null;location:string;on_hand:number;low_stock_threshold:number};
type ModelPart={id:string;model:string;part_name:string;part_number:string|null;quantity:number;location:string|null;material_type:string;active:boolean};
const models=['600','660','800','860','1200SJP','1250','1350SJP','1500SJ'];
const materials=['Base Boom','Small / Mid Boom','Big / Mid Boom','Fly Boom','Push Tube','Push Tube (2)','Push Tube (3)','Telescope','Telescope Cylinder','Power Track T/T','Power Track Upper'];
function norm(v:string|null|undefined){return(v??'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function samePart(a:string,b:string){const x=norm(a),y=norm(b);if(x===y)return true;if(x==='smallmidboom')return ['smallmidboom','outermidsmallmid'].includes(y);if(x==='bigmidboom')return ['bigmidboom','innermidbigmid'].includes(y);return false}

export default function GregInventoryCheck(){
 const[stock,setStock]=useState<InventoryItem[]>([]),[parts,setParts]=useState<ModelPart[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){const[inv,mp]=await Promise.all([supabase.from('inventory').select('id, material_type, material_name, part_number, location, on_hand, low_stock_threshold').eq('material_type','Boom'),supabase.from('model_parts').select('id, model, part_name, part_number, quantity, location, material_type, active').eq('material_type','Boom').eq('active',true)]);setStock((inv.data??[])as InventoryItem[]);setParts((mp.data??[])as ModelPart[]);setError(inv.error||mp.error?'Unable to load all inventory data.':'');setLoading(false)}
 useEffect(()=>{load();const channel=supabase.channel('greg-inventory-matrix').on('postgres_changes',{event:'*',schema:'public',table:'inventory'},load).on('postgres_changes',{event:'*',schema:'public',table:'model_parts'},load).subscribe();return()=>{supabase.removeChannel(channel)}},[]);
 function cell(model:string,material:string){const configured=parts.filter(p=>norm(p.model)===norm(model)&&samePart(material,p.part_name));if(!configured.length)return null;const part=configured[0];const inventory=stock.find(s=>(part.part_number&&norm(s.part_number)===norm(part.part_number))||(!part.part_number&&samePart(part.part_name,s.material_name)));return{partNumber:part.part_number,qty:inventory?.on_hand??null,location:inventory?.location||part.location||null,threshold:inventory?.low_stock_threshold??null}}
 const stats=useMemo(()=>{const cells=models.flatMap(model=>materials.map(material=>cell(model,material))).filter(Boolean) as NonNullable<ReturnType<typeof cell>>[];return{models:models.length,records:cells.length,inStock:cells.filter(c=>c.qty!==null&&c.qty>0).length,low:cells.filter(c=>c.qty!==null&&c.qty>0&&c.threshold!==null&&c.qty<=c.threshold).length,out:cells.filter(c=>c.qty===0).length}},[parts,stock]);
 return <section className="sectionBlock" id="greg-inventory-check"><div className="requestFlowHeader"><div><p className="eyebrow">Inventory Check</p><h2>Boom Materials — All Models</h2><p className="dashboardRole">Read-only model-by-model view of quantity in stock and pickup location. Blank cells mean that material has not been configured for that model.</p></div></div>
 <div className="dashboardGrid supervisorCoreGrid"><article className="metricCard"><span>Models</span><strong>{models.length}</strong><p>600 through 1500SJ.</p></article><article className="metricCard"><span>Configured Parts</span><strong>{loading?'—':stats.records}</strong><p>Model-part records.</p></article><article className="metricCard"><span>In Stock</span><strong>{loading?'—':stats.inStock}</strong><p>Configured parts with stock.</p></article><article className="metricCard"><span>Low / Out</span><strong>{loading?'—':`${stats.low} / ${stats.out}`}</strong><p>Low stock / out of stock.</p></article></div>
 {error&&<p className="requestMessage">{error}</p>}
 <div className="modelPartsTableWrap" style={{marginTop:14,overflowX:'auto'}}><table className="modelPartsTable" style={{minWidth:1450}}><thead><tr><th rowSpan={2}>Material / Part</th>{models.map(model=><th key={model} colSpan={2} style={{textAlign:'center'}}>{model}</th>)}</tr><tr>{models.flatMap(model=>[<th key={`${model}-qty`}>Qty</th>,<th key={`${model}-loc`}>Location</th>])}</tr></thead><tbody>{loading?<tr><td colSpan={17}>Loading model inventory...</td></tr>:materials.map(material=><tr key={material}><td><strong>{material}</strong></td>{models.flatMap(model=>{const c=cell(model,material);const low=c&&c.qty!==null&&c.qty>0&&c.threshold!==null&&c.qty<=c.threshold,out=c?.qty===0;return[<td key={`${model}-${material}-qty`} title={c?.partNumber?`Part # ${c.partNumber}`:'Part number not entered'}><strong>{c?.qty??'—'}</strong>{out&&<small className="cardAction"> Out</small>}{low&&<small className="cardAction"> Low</small>}</td>,<td key={`${model}-${material}-loc`}>{c?.location||'—'}</td>]})}</tr>)}</tbody></table></div>
 <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><span className="priorityBadge">In Stock</span><span className="priorityBadge">Low Stock</span><span className="priorityBadge priorityUrgent">Out of Stock</span><span className="priorityBadge">— Not configured / not entered</span></div>
 <p className="scheduleFootnote">Models: 600 · 660 · 800 · 860 · 1200SJP · 1250 · 1350SJP · 1500SJ. Quantities come only from live Boom inventory; model/part relationships come from Material Master Setup. No stock quantities are invented.</p></section>;
}
