'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import LanguageToggle, { getLanguage, translations, LineFlowLanguage } from '../../components/LanguageToggle';

type DemoAccount = { name: string; role: string; group: string; internalUsername: string };
const users: Record<string, DemoAccount> = {
 tammy:{name:'Operations Leadership',role:'Operations Leadership / System Administrator',group:'supervisor',internalUsername:'tammy'},chance:{name:'Houston Supervisor',role:'Houston Supervisor / System Administrator',group:'supervisor',internalUsername:'chance'},debbie:{name:'Planner',role:'Planner / System Administrator',group:'supervisor',internalUsername:'debbie'},jose:{name:'Boom Line Material Specialist',role:'Boom Line Material Specialist',group:'specialist',internalUsername:'jose'},greg:{name:'Boom Material Handler',role:'Boom Material Handler / Combi Lift',group:'handler',internalUsername:'greg'},storm:{name:'Hood Material Handler',role:'Hood Material Handler / Forklift',group:'handler',internalUsername:'tristen'},tristen:{name:'Hood Material Handler',role:'Hood Material Handler / Forklift',group:'handler',internalUsername:'tristen'},byrd:{name:'Byrd',role:'Shipping & Receiving Specialist',group:'shipping',internalUsername:'byrd'},mike:{name:'Mike',role:'Boom Assembly Line Supervisor',group:'line',internalUsername:'line1'},line2:{name:'Line 2',role:'Assembly Line User',group:'line',internalUsername:'line2'},line3:{name:'Line 3',role:'Assembly Line User',group:'line',internalUsername:'line3'},line4:{name:'Line 4',role:'Assembly Line User',group:'line',internalUsername:'line4'}
};
export default function LoginPage(){
 const router=useRouter();const[selectedRole,setSelectedRole]=useState('');const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[language,setLanguage]=useState<LineFlowLanguage>('en');const t=translations[language];
 useEffect(()=>{setLanguage(getLanguage());const role=new URLSearchParams(window.location.search).get('role')||'';setSelectedRole(['line','handler','supervisor','specialist','shipping'].includes(role)?role:'')},[]);
 function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();const key=username.trim().toLowerCase().replace(/\s+/g,'');const user=users[key];if(!user||password!=='12345'){setError(t.invalidLogin);return}if(selectedRole&&user.group!==selectedRole){setError(t.wrongRole);return}localStorage.setItem('lineflowUser',JSON.stringify({name:user.name,role:user.role,group:user.group,username:user.internalUsername}));router.push('/dashboard')}
 return <main className="shell authShell"><style>{`.authLanguageRow{display:flex;justify-content:flex-end;margin-bottom:18px}.languageToggle{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid var(--border);border-radius:999px;background:#0b1728;font-size:.78rem}.languageChoice{border:0;background:transparent;color:var(--muted);font-weight:800;cursor:pointer;padding:3px 5px}.languageChoice.activeLanguage{color:var(--accent)}.languageDivider{color:var(--border)}`}</style><section className="authCard"><div className="authLanguageRow"><LanguageToggle onChange={setLanguage}/></div><div className="brandRow"><div className="logoMark">LF</div><div><p className="eyebrow">LineFlow AI · Demo</p><h1 className="authTitle">{t.signIn}</h1></div></div><p className="authCopy">{t.loginCopy}</p><form className="loginForm" onSubmit={handleSubmit}><label>{t.username}<input autoComplete="username" value={username} onChange={e=>{setUsername(e.target.value);setError('')}} placeholder={t.enterUsername}/></label><label>{t.password}<input type="password" autoComplete="current-password" value={password} onChange={e=>{setPassword(e.target.value);setError('')}} placeholder="12345"/></label>{error?<p className="formError">{error}</p>:null}<button className="primaryButton fullButton" type="submit">{t.signIn}</button></form><p className="authCopy" style={{marginTop:12,fontSize:'.86rem',lineHeight:1.6}}><strong>{t.demoUsernames}</strong> tammy · chance · debbie · jose · greg · storm · tristen · byrd · mike · line2 · line3 · line4</p><p className="authCopy" style={{marginTop:4}}>{t.demoPassword} <strong>12345</strong></p><div className="actions"><button className="secondaryButton fullButton" type="button" onClick={()=>router.push('/')}>{t.backHome}</button></div></section></main>
}
